{% set version = "4.14" %}

package:
  name: cgal-cpp
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.zip
  sha256: b5d149726266f5f87d84f896aec672e07846ebf8b2ba2a33e696feaa2e250ef3

build:
  number: 1
  # mpfr only supports vc14
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp {{ boost_version }}
    - mpfr
    - eigen
  run:
    - boost-cpp {{ boost_version }}
    - mpfr
    - eigen

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja
  files:
    - test
  commands:
    - echo on  # [win]
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [unix]
    - conda inspect objects $PKG_NAME  # [osx]

    # Builds a simple program
    - cd test

    - mkdir build_default
    - cd build_default
    - cmake .. -G"%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  # [win]
    - cmake .. -G"$CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  # [unix]
    - cmake --build . --config Release
    - ./test_  # [unix]
    - Release\\test_.exe  # [win]
    - cd ..

    - mkdir build_ninja
    - cd build_ninja
    - cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - ./test_  # [unix]
    - test_.exe  # [win]

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - tadeu
