{% set version = "5.6.1" %}

package:
  name: cgal-cpp
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/v{{ version }}/CGAL-{{ version }}.tar.xz
  sha256: cdb15e7ee31e0663589d3107a79988a37b7b1719df3d24f2058545d1bcdd5837
  patches:
    - pr7635.patch
      # upstream patch from https://github.com/CGAL/cgal/pull/7635

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - libboost-devel
    - mpfr
    - eigen
  run:
    # cgal needs boost headers & metadata at runtime to be usable
    - libboost-devel
    - mpfr
    - eigen

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja
  files:
    - test
  commands:
    - echo on  # [win]
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]

    # Builds a simple program
    - cd test

    - mkdir build_default
    - cd build_default
    - cmake .. -G"NMake Makefiles" -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  # [win]
    - cmake .. -G"$CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  # [unix]
    - cmake --build . --config Release
    - ./test_  # [unix]
    - test_.exe  # [win]
    - cd ..

    - mkdir build_ninja
    - cd build_ninja
    - cmake .. -G"Ninja" -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_BUILD_TYPE=Release  # [win]
    - cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release  # [unix]
    - cmake --build . --config Release
    - ./test_  # [unix]
    - test_.exe  # [win]

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  license_file: LICENSE
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - tadeu
    - lrineau
